"""Chat configuration module"""
from .system_prompts import (
    PERSONALITY_TRAITS,
    RESPONSE_FORMAT_RULES,
    SYNTHESIS_INSTRUCTIONS,
    CLASSIFICATION_PROMPT_TEMPLATE,
    SYNTHESIS_PROMPT_TEMPLATE
)

__all__ = [
    'PERSONALITY_TRAITS',
    'RESPONSE_FORMAT_RULES',
    'SYNTHESIS_INSTRUCTIONS',
    'CLASSIFICATION_PROMPT_TEMPLATE',
    'SYNTHESIS_PROMPT_TEMPLATE'
]