version: "3.9"
services:
  sidecar:
    build:
      context: ./python-sidecar
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./python-sidecar:/app
    environment:
      - UVICORN_RELOAD=true
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - OPENAI_MAX_TOKENS=${OPENAI_MAX_TOKENS}
      - OPENAI_TEMPERATURE=${OPENAI_TEMPERATURE}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - ANTHROPIC_MODEL=${ANTHROPIC_MODEL}
      - ANTHROPIC_MAX_TOKENS=${ANTHROPIC_MAX_TOKENS}
      - ANTHROPIC_TEMPERATURE=${ANTHROPIC_TEMPERATURE}
      - PLAYBOOK_EXTRACTION_PROVIDER=${PLAYBOOK_EXTRACTION_PROVIDER}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_INDEX=${PINECONE_INDEX}
      - PINECONE_ENVIRONMENT=${PINECONE_ENVIRONMENT}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - SUPABASE_BUCKET=documents
